blueprint:
  name: Automatic scene activation based on motion and illuminance
  description: >
    Turns on lights when there is motion and it is dark enough, or when it
    becomes dark while motion is detected. Chooses a scene based on time of
    day (day / night / inbetween). Optionally only activates if a given
    light (or light group) is currently off.
  domain: automation
  source_url: https://raw.githubusercontent.com/w-Teilchen/homeassistant_blueprints/refs/heads/main/light_activation_blueprint.yaml

  input:
    motion_sensor:
      name: Motion sensor or motion group
      description: >
        Binary sensor that is ON when there is motion in the room.
        This can also be a binary_sensor group.
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy

    illuminance_sensor:
      name: Illuminance sensor
      description: >
        Sensor providing room brightness in lux. If you have multiple sensors,
        use a template / helper that combines them and select it here.
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    state_check_light:
      name: Light to check for "only if off"
      description: >
        Single light or light group used to check if the lights are currently
        off. Typically this is the same group you actually control. Required
        if "Only if lights are off" is enabled.
      selector:
        entity:
          domain: light

    only_if_lights_off:
      name: Only if lights are off
      description: >
        If enabled, the automation will only run when the state_check_light
        is currently off. If disabled, it will always run when triggered.
      default: true
      selector:
        boolean: {}

    dark_threshold:
      name: Dark threshold (lux)
      description: >
        When illuminance is below this value, the room is considered dark.
      default: 30
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: lux
          mode: slider

    on_transition:
      name: On transition (seconds)
      description: >
        Fade-in duration when turning on scenes.
      default: 1
      selector:
        number:
          min: 0
          max: 30
          step: 1
          unit_of_measurement: seconds
          mode: slider

    day_scene:
      name: Day scene
      description: >
        Scene to activate during daytime (between day_start_time and day_end_time).
      selector:
        entity:
          domain: scene

    dawn_and_dusk_scene:
      name: Scene for times inbetween day and night
      description: >
        When it is neither day nor night.
      selector:
        entity:
          domain: scene

    night_scene:
      name: Night scene
      description: >
        Scene to activate during the night.
      selector:
        entity:
          domain: scene

    night_end_time:
      name: Night end time
      description: >
        End of the night window (before this time the night scene is active).
      default: "05:30:00"
      selector:
        time: {}

    day_start_time:
      name: Day start time
      description: >
        Start of daytime window (used for the day_scene).
      default: "06:30:00"
      selector:
        time: {}

    day_end_time:
      name: Day end time
      description: >
        End of daytime window (used for the day_scene).
      default: "20:00:00"
      selector:
        time: {}

    night_start_time:
      name: Night start time
      description: >
        Start of the night window (after this time the night scene is active).
      default: "23:00:00"
      selector:
        time: {}

    snapshot_scene:
      name: Snapshot scene ID
      description: >
        The same scene ID used in the deactivation blueprint (e.g.,
        "snapshot_living_room"). When restoring because the lights were changed
        recently, this scene will be used to restore the exact light states.
      default: snapshot_room
      selector:
        text: {}

    last_light_change_timestamp:
      name: Last light change timestamp (input_datetime)
      description: >
        Same input_datetime helper as used in the deactivation blueprint.
        It is updated whenever the light changes.
        If the last light change happened recently, the snapshot scene can be restored
        instead of selecting a day/night scene.
      default: input_datetime.none
      selector:
        entity:
          domain: input_datetime

    restore_window:
      name: Snapshot restore window (minutes)
      description: >
        If motion triggers within this many minutes after the last auto-off,
        restore the snapshot scene.
      default: 10
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: minutes
          mode: slider

variables:
  only_if_lights_off_var: !input only_if_lights_off
  state_light: !input state_check_light
  snapshot_scene_id: !input snapshot_scene
  last_light_change_ts_entity: !input last_light_change_timestamp
  restore_window_min: !input restore_window

mode: single

trigger:
  # 1) Motion starts
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: motion

  # 2) It becomes dark enough
  - platform: numeric_state
    entity_id: !input illuminance_sensor
    below: !input dark_threshold
    id: dark

condition:
  # Must be dark enough
  - condition: numeric_state
    entity_id: !input illuminance_sensor
    below: !input dark_threshold

  # Must have motion currently
  - condition: state
    entity_id: !input motion_sensor
    state: "on"

  # Allow activation if:
  # - lights are off (if only_if_lights_off is enabled), OR
  # - only_if_lights_off is disabled
  - condition: template
    value_template: >
      {% if only_if_lights_off_var %}
        {{ is_state(state_light, 'off') }}
      {% else %}
        true
      {% endif %}

action:
  - choose:
      # Restore snapshot if the last light change is recent enough
      - conditions:
          - condition: template
            value_template: >
              {% if last_light_change_ts_entity != 'input_datetime.none' %}
                {% set last = states(last_light_change_ts_entity) %}
                {% set mins = restore_window_min | int(0) %}
                {{ mins > 0 and last not in ['unknown','unavailable','none','']
                   and (as_timestamp(now()) - as_timestamp(last)) < (mins * 60) }}
              {% else %}
                false
              {% endif %}
        sequence:
          - service: scene.turn_on
            target:
              entity_id: "scene.{{ snapshot_scene_id }}"
            data:
              transition: !input on_transition
          - service: input_datetime.set_datetime
            target:
              entity_id: !input last_light_change_timestamp
            data:
              datetime: "{{ now().isoformat() }}"

      # Daytime: between day_start and day_end -> day_scene
      - conditions:
          - condition: time
            after: !input day_start_time
            before: !input day_end_time
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input day_scene
            data:
              transition: !input on_transition
          - service: input_datetime.set_datetime
            target:
              entity_id: !input last_light_change_timestamp
            data:
              datetime: "{{ now().isoformat() }}"

      # Very early: before night_end_time -> night_scene
      - conditions:
          - condition: time
            before: !input night_end_time
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input night_scene
            data:
              transition: !input on_transition
          - service: input_datetime.set_datetime
            target:
              entity_id: !input last_light_change_timestamp
            data:
              datetime: "{{ now().isoformat() }}"

      # Very late: after night_start_time -> night_scene
      - conditions:
          - condition: time
            after: !input night_start_time
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input night_scene
            data:
              transition: !input on_transition
          - service: input_datetime.set_datetime
            target:
              entity_id: !input last_light_change_timestamp
            data:
              datetime: "{{ now().isoformat() }}"

    # Default: all other times -> dawn_and_dusk_scene
    default:
      - service: scene.turn_on
        target:
          entity_id: !input dawn_and_dusk_scene
        data:
          transition: !input on_transition
      - service: input_datetime.set_datetime
        target:
          entity_id: !input last_light_change_timestamp
        data:
          datetime: "{{ now().isoformat() }}"
