blueprint:
  name: Automatic light deactivation with fade-out
  description: >
    Turns off lights when there is no motion for a configurable time or when it
    is bright enough. Uses a fade-out transition. Requires a motion sensor (or group),
    an illuminance sensor, the target light(s), and an input_datetime helper used to
    store the last time the lights were changed.
  domain: automation
  source_url: https://raw.githubusercontent.com/w-Teilchen/homeassistant_blueprints/refs/heads/main/light_deactivation_blueprint.yaml
  
  input:
    motion_sensor:
      name: Motion sensor or motion group
      description: >
        Binary_sensor that is ON when there is motion in the room (can be a group
        of multiple motion sensors).
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy

    illuminance_sensor:
      name: Illuminance sensor
      description: >
        Sensor providing the room brightness in lux. If you want to use multiple
        sensors, create a template or min/avg helper sensor and use that here.
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    target_lights:
      name: Lights to snapshot and control
      description: >
        Light or light group that should be snapshot.
      selector:
        target:
          entity:
            domain: light

    snapshot_scene:
      name: Snapshot scene (scene entity)
      description: >
        An existing scene entity that will be overwritten on each run to store a
        snapshot of the current light states. This makes it easier to inspect/debug
        the snapshot via the UI.
      selector:
        entity:
          domain: scene

    # --- Timing / thresholds ---
    no_motion_delay:
      name: Delay before fading out after no motion
      description: >
        How long there must be no motion before starting a fade-out.
      default: 00:01:00
      selector:
        duration: {}

    bright_delay:
      name: Delay before fading out after it is bright enough
      description: >
        How long illuminance must stay above the threshold before starting a fade-out.
      default: 00:00:30
      selector:
        duration: {}

    brightness_threshold:
      name: Brightness threshold (lux)
      description: >
        When illuminance rises above this value, the lights will start to fade off.
      default: 60
      selector:
        number:
          min: 1
          max: 1000
          step: 1
          unit_of_measurement: lux
          mode: slider

    # --- Transitions ---
    off_transition:
      name: Off transition (seconds)
      description: >
        Duration of the fade-out when turning the lights off.
      default: 10
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: seconds
          mode: slider

    # --- Helpers ---
    last_light_change_timestamp:
      name: Last light change timestamp (input_datetime)
      description: >
        Input_datetime helper updated whenever this blueprint changes the lights
        (turning them off). This can be used by the activation blueprint to decide
        whether the snapshot scene should be restored within a configurable time
        window.
      selector:
        entity:
          domain: input_datetime

variables:
  off_transition: !input off_transition
  target_lights_input: !input target_lights
  snapshot_scene_entity: !input snapshot_scene
  target_light_entity_ids: >
    {% set ids = target_lights_input.entity_id if (target_lights_input is defined and target_lights_input.entity_id is defined) else target_lights_input %}
    {{ ids if ids is list else ([ids] if ids is string else []) }}

mode: restart
max_exceeded: silent

trigger:
  # 1) When there was no motion for the configured time
  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: !input no_motion_delay
    id: no_motion

  # 2) When it becomes bright enough
  - platform: numeric_state
    entity_id: !input illuminance_sensor
    above: !input brightness_threshold
    for: !input bright_delay
    id: bright

condition:
  # Only run if at least one of the targeted light entities is currently on
  - condition: template
    value_template: >
      {{ target_light_entity_ids | select('is_state', 'on') | list | count > 0 }}

  # Avoid fading out if motion returned right before the action runs
  - condition: state
    entity_id: !input motion_sensor
    state: "off"

action:
  # Capture the current light states into the selected scene entity
  - service: scene.create
    data:
      scene_id: "{{ snapshot_scene_entity.split('.', 1)[1] }}"
      snapshot_entities: {{ target_light_entity_ids }}

  # Store the time of this automatic light change (used for restore window logic)
  - service: input_datetime.set_datetime
    target:
      entity_id: !input last_light_change_timestamp
    data:
      datetime: "{{ now().isoformat() }}"

  # Start fading out the lights
  - service: light.turn_off
    target: !input target_lights
    data:
      transition: !input off_transition
